export const AuthApi = {
  login: "/Auth/Login",
  resendCode: "/Auth/ResendCode",
  verifyCode: "/Auth/VerifyCode",
  register: "/Auth/Register",
  passwordRenew: "/Auth/PasswordRenew",
  resetPassword: "/Auth/ResetPassword",
  forgotPassword: "/Auth/ForgotPassword",
  changeGsmNoLogin: "/Auth/ChangeGsmNoLogin",
  changePassword: "/Auth/ChangePassword",
  changeGsm: "/Auth/ChangeGsm",
  changeEmail: "/Auth/ChangeEmail",
  changeToken: "/Auth/ChangeToken",
  rechangeToken: "/Auth/ReChangeToken",
  logout: "/Auth/Logout",
};
